version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped 