name: Deploy Summarizer App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Copy files to EC2 using rsync (exclude .git and .github)
      run: |
        rsync -avz --exclude='.git' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/${{ secrets.APP_NAME }}/

    - name: Build and restart Docker container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/${{ secrets.APP_NAME }}
          docker stop summarizer || true
          docker rm summarizer || true
          docker build -t summarizer .
          docker run -d --name summarizer -p 5001:5001 summarizer
        EOF
